name: todo_calendar
description: "Manage Tasks."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  uuid: ^4.4.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.2
  table_calendar: ^3.1.2
  timezone: ^0.9.4
  url_launcher: ^6.3.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"
flutter:

  uses-material-design: true
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf
